# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: GMGI221 - Automatisering av GIS-prosesser
author: Håvard Wallin Aagesen
copyright: "2024"
logo: logo.png
exclude_patterns: [ "**.ipynb_checkpoints"]
#only_build_toc_files: true
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: gmgi221.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
parse:
   myst_url_schemes: [mailto, http, https]
# Information about where the book exists on the web
repository:
  url: https://github.com/haavardaagesen/gmgi221  # Online location of your book
  #path_to_book: content  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)
  
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - custom.css
  extra_footer: |
    <p>This course is heavily based on the <a href="https://autogis-site.readthedocs.io/en/latest/" target="_blank">Automating GIS processes</a> course at the University of Helsinki.</p>

